name: Docker Build and Scan

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Dummy SSL for Build
      # We create these INSIDE the weather-app directory 
      # so the Docker COPY command finds them.
      run: |
        touch ./weather-app/nginx-selfsigned.crt
        touch ./weather-app/nginx-selfsigned.key
        echo "✅ Created dummy files in ./weather-app/"
        ls -l ./weather-app/

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build image
      # The '.' at the end of the command tells Docker to look 
      # INSIDE the weather-app folder for its files.
      run: |
        docker build -t weather-app:test ./weather-app/